[build-system]
requires = ["setuptools", "wheel", "pybind11>=2.6"]
build-backend = "setuptools.build_meta"

[project]
name = "ciwheels-example"
version = "0.0.1"
description = "A test project for cibuildwheel with C++ extensions (NEON/AVX)"
readme = "README.md"
requires-python = ">=3.7"
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Topic :: Software Development :: Build Tools",
]
